codecov:
  strict_yaml_branch: master  # only use the latest copy on master branch
coverage:
  range: 50..100
  status:
    project:
      default:
        target: 90
        threshold: 10
    patch:
      default:
        threshold: 5
