version: '3.2'
services:
  master-node:
    image: "amy-master-node"
    depends_on:
     - "broker"
    environment:
      - AMY_SERVER_CONFIG_SERVER_URL=http://master-node
      - AMY_MQTT_CONFIG_BROKER_HOST=tcp://broker
    ports:
     - "80:80"
    container_name: master-node
  broker:
    image: "eclipse-mosquitto"
